### ISSUE TITLE
Directories not found under llmware_data on windows 11 

### ISSUE THREAD

**Issue by JEHollierJr** [llmware-ai/llmware#209]
I did a clean install of llmware 1.12 and there are some directories that are not created under llmware_data.
I am running python 3.11 with vs code.

Under examples\Getting_Started
- getting_started_with_rag.py
-  > Creating library 'Agreements'...
Traceback (most recent call last):
  File "d:\home\john\Projects\llmware-main\examples\Getting_Started\getting_started_with_rag.py", line 55, in <module>
    end_to_end_rag(model_name, vector_db="faiss")
  File "d:\home\john\Projects\llmware-main\examples\Getting_Started\getting_started_with_rag.py", line 18, in end_to_end_rag
    library.add_files(os.path.join(sample_files_path,"Agreements"))
  File "C:\Users\jehol\AppData\Local\Programs\Python\Python311\Lib\site-packages\llmware\library.py", line 357, in add_files
    parsing_results = Parser(library=self).ingest(input_folder_path,dupe_check=True)
                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jehol\AppData\Local\Programs\Python\Python311\Lib\site-packages\llmware\parsers.py", line 98, in __init__
    os.mkdir(parser_tmp_work_folder)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\jehol\\llmware_data\\tmp\\parser_tmp\\'

I created the directory llmware\tmp and reran the example and I got the following error

 > Generating CSV report...
Traceback (most recent call last):
  File "d:\home\john\Projects\llmware-main\examples\Getting_Started\getting_started_with_rag.py", line 55, in <module>
    end_to_end_rag(model_name, vector_db="faiss")
  File "d:\home\john\Projects\llmware-main\examples\Getting_Started\getting_started_with_rag.py", line 42, in end_to_end_rag
    report_data = prompter.send_to_human_for_review()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jehol\AppData\Local\Programs\Python\Python311\Lib\site-packages\llmware\prompts.py", line 1028, in send_to_human_for_review
    output = HumanInTheLoop(prompt=self).export_current_interaction_to_csv(output_path=output_path,report_name=output_fn)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jehol\AppData\Local\Programs\Python\Python311\Lib\site-packages\llmware\prompts.py", line 1882, in export_current_interaction_to_csv
    output = PromptState(self.prompt).generate_interaction_report_current_state(output_path=output_path,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jehol\AppData\Local\Programs\Python\Python311\Lib\site-packages\llmware\resources.py", line 1072, in generate_interaction_report_current_state
    with open(report_fp, 'w', encoding='utf-8', newline='') as csvfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jehol\\llmware_data\\prompt_history\\interaction_report_2023-12-21_084950.csv'

i create the directory llmware_data\prompt_history manually re-ran the example and it completed successfully.

John

**Comment by doberst** [comment]
Fixed and merged - see separate comment.   Thanks for catching this!
