### ISSUE TITLE
error while running Prompts\document_summarizer.py

### ISSUE THREAD

**Issue by JEHollierJr** [llmware-ai/llmware#211]
- error in document_summarizer.py
   
   Traceback (most recent call last):
  File "d:\home\john\Projects\llmware-main\examples\Prompts\document_summarizer.py", line 87, in <module>
    summary_library = test_summarize_document_from_library(llm_model)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\home\john\Projects\llmware-main\examples\Prompts\document_summarizer.py", line 59, in test_summarize_document_from_library
    summary = prompter.summarize_document_from_library(lib,filename=fn)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jehol\AppData\Local\Programs\Python\Python311\Lib\site-packages\llmware\prompts.py", line 872, in summarize_document_from_library
    output_text += entries["llm_response"] + "\n"
                   ~~~~~~~^^^^^^^^^^^^^^^^
   KeyError: 'llm_response'

I added the following check in prompts.py at line 870 on my system and it ran fine.
            for i, entries in enumerate(response):
                # print("update: summaries - ", i, entries)
                if 'llm_response' in entries:
                    output_text += entries["llm_response"] + "\n"

John

**Comment by JEHollierJr** [comment]
This example was encountered on windows 11 pro after a clean install of llmware 1.12

**Comment by doberst** [comment]
Good catch - Thank you - fixed and merged into main.
