### ISSUE TITLE
error while running Prompts\fact_checking.py

### ISSUE THREAD

**Issue by JEHollierJr** [llmware-ai/llmware#212]
I encountered an error while running Prompts\fact_checking.py on windows 11
i did a clean installed of llmware 1.12 and ran the examples.

Prompts\fact_checking.py
   Traceback (most recent call last):
  File "d:\home\john\Projects\llmware-main\examples\Prompts\fact_checking.py", line 76, in <module>
    contract_analysis_with_fact_checking(hf_model_list[0])
  File "d:\home\john\Projects\llmware-main\examples\Prompts\fact_checking.py", line 31, in contract_analysis_with_fact_checking
    source = prompter.add_source_document(contracts_path, contract, query=research["topic"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jehol\AppData\Local\Programs\Python\Python311\Lib\site-packages\llmware\prompts.py", line 400, in add_source_document
    output = Parser().parse_one(input_fp,input_fn)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jehol\AppData\Local\Programs\Python\Python311\Lib\site-packages\llmware\parsers.py", line 1870, in parse_one
    ParserState().save_parser_output(self.parser_job_id, output)
  File "C:\Users\jehol\AppData\Local\Programs\Python\Python311\Lib\site-packages\llmware\resources.py", line 708, in save_parser_output
    for entry_dict in parser_output:
  TypeError: 'NoneType' object is not iterable

john

**Comment by JEHollierJr** [comment]
This is a problem with DS_Store files being in the directory with the sample files.  Windows will treat this like any other file and add it to the list of files to process.  It is not in a format expected, so it chokes.  I deleted the file and the example completed successfully.

**Comment by doberst** [comment]
Improvement in defensive code to better handle this error has been added and merged into the main branch.   It will also be in the next pip version 0.1.13.
