### ISSUE TITLE
Directory llmware_data\query_history missing encountered when running Retrieval\query_state.py

### ISSUE THREAD

**Issue by JEHollierJr** [llmware-ai/llmware#213]
I encountered this error after a clean install of llmware 1.12 on windows 11
the problem is the directory llmware_data\query_history was not created.

  Traceback (most recent call last):
  File "d:\home\john\Projects\llmware-main\examples\Retrieval\query_state.py", line 60, in <module>
    query_state_and_export(lib)
  File "d:\home\john\Projects\llmware-main\examples\Retrieval\query_state.py", line 41, in query_state_and_export        
    query.save_query_state()
  File "C:\Users\jehol\AppData\Local\Programs\Python\Python311\Lib\site-packages\llmware\retrieval.py", line 236, in save_query_state
    QueryState(self).save_state()
  File "C:\Users\jehol\AppData\Local\Programs\Python\Python311\Lib\site-packages\llmware\resources.py", line 1224, in save_state
    outfile = open(fp, "w", encoding='utf-8')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jehol\\llmware_data\\query_history\\query_7457a169-7318-404b-a005-3387b8a17268.jsonl'
	
I created directory llmware_data\query_history and re ran query_state.py
query_state.py ran successfully

John

**Comment by doberst** [comment]
Hi John - thanks for calling this out - we will dig into it right away.   Sorry you have run into some issues.   We will look first at the missing filepaths, and see if a regression got introduced with 1.12 on those two file paths on Windows in particular.

**Comment by doberst** [comment]
Hi John - thanks for catching a really useful bug (not enough defensive code if paths deleted/changed inside the main llmware path)... this fix has been pushed and merged to the main branch - will be posted in the next pip install release by the weekend ...
