### ISSUE TITLE
 AttributeError: module 'openai' has no attribute 'api_base'. Did you mean: 'api_type'?

### ISSUE THREAD

**Issue by SouSingh** [llmware-ai/llmware#304]
Traceback (most recent call last):
  File "D:\DCPR\app.py", line 53, in <module>
    contract_analysis_w_fact_checking(text)
  File "D:\DCPR\app.py", line 28, in contract_analysis_w_fact_checking
    responses = prompter.prompt_with_source(research["prompt"], prompt_name="just_the_facts", temperature=0.3)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\site-packages\llmware\prompts.py", line 549, in prompt_with_source
    response_dict = self.prompt_main(prompt,prompt_name=self.prompt_type,
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\site-packages\llmware\prompts.py", line 735, in prompt_main
    output_dict = self.llm_model.inference(prompt, inference_dict=inference_dict)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python310\lib\site-packages\llmware\models.py", line 1268, in inference
    openai_api_base_entering_state = openai.api_base
AttributeError: module 'openai' has no attribute 'api_base'. Did you mean: 'api_type'?

inside models.py change api_base to api_type

**Comment by doberst** [comment]
@SouSingh - thanks for raising this.   What version of the openai python api are you using?    Keeping open if anyone else has encountered this issue.

**Comment by doberst** [comment]
Closing the issue as resolved + inactive
